// Disk IO for human labels. Kept apart from the pure schema module so the
// verdict logic stays testable without touching a filesystem.

import fs from "node:fs/promises";
import path from "node:path";
import { EMPTY_LABELS, type LabelsFile, LabelsFileSchema } from "../schemas/label.js";

export const LABELS_PATH = path.resolve("videos", "labels.json");

/**
 * Read the labels file. A missing file is the normal first-run state, not an
 * error. A CORRUPT file is different: returning empty there would present as
 * "no labels yet" and the next write would overwrite hand-made verdicts that
 * cannot be regenerated by any pipeline step, so it throws instead.
 */
export async function loadLabels(file: string = LABELS_PATH): Promise<LabelsFile> {
  let raw: string;
  try {
    raw = await fs.readFile(file, "utf8");
  } catch {
    return EMPTY_LABELS;
  }
  const parsed = LabelsFileSchema.safeParse(JSON.parse(raw));
  if (!parsed.success) throw new Error(`labels.json is present but unreadable: ${parsed.error.message.slice(0, 200)}`);
  return parsed.data;
}

/** Write via temp + rename so an interrupted save cannot truncate the only copy. */
export async function saveLabels(data: LabelsFile, file: string = LABELS_PATH): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  const tmp = `${file}.tmp`;
  await fs.writeFile(tmp, `${JSON.stringify(data, null, 2)}\n`, "utf8");
  await fs.rename(tmp, file);
}
